### ISSUE TITLE
Test Conditions for CNC  ESP32

### ISSUE THREAD

**Issue by ClausElectronics** [positron96/ESP32_CNC_Pendant#3]
Hallo!
Thank you very much for doing so much in these topics!

I want to control my CNC with esp32 and its web interface. I built up the system and now I want to test it. 
FIrst for example I want to test only x-axis, then y-axis and so on - without the whole cnc - only on  the table.

My questions: 
Which Input-pins are connected to HIGH, which to LOW on the ESP32 to do that? 
E.g. . X-Limit=Y-Limit=Z-Limit = Low (0 Volts)
or: Abort= H (3.3 Volts),...

Are there any test pattern to check that?

Thank you in advance!

**Comment by positron96** [comment]
Hi. Let me clarify this: in this project the ESP32 does not control the steppers. ESP32 sends GCodes via UART to an Arduino that is running GRBL that controls the motors. If you need to only have an ESP32 in your setup, this is not the right project.

**Comment by ClausElectronics** [comment]
Hi, thanks for the fast answer, you are write! I will look for the right one ;)

**Comment by ClausElectronics** [comment]
Sorry, it was the wrong project
