### ISSUE TITLE
Pin ESP32 SDK version

### ISSUE THREAD

**Issue by positron96** [positron96/ESP32_CNC_Pendant#5]
For #4, current versions do not seem to work out of the box. Need to pin my working version

**Comment by amjadali56** [comment]
For me  ESP32 SDK worked as:
`[platformio]

default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32@3.5.0
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
   https://github.com/me-no-dev/ESPAsyncWebServer.git     ; New ESPAsync Web Server work better......
    ArduinoJson@6.19.2
    U8g2@2.32.10
    etlcpp/Embedded Template Library @ ^19.3.5

upload_port = COM5
monitor_speed = 115200
monitor_port = COM5

`

**Comment by positron96** [comment]
@amjadali56 great, thank you very much for sharing that. I have 3.3.2, so if the newer 3.5 works, I'll use that.
