### ISSUE TITLE
hello errors

### ISSUE THREAD

**Issue by andy0983** [positron96/ESP32_CNC_Pendant#6]
hello errors when compiling the project with related to:
.pio/libdeps/denky32/FreeRTOS-Kernel/event_groups.c: Assembler messages:
.pio/libdeps/denky32/FreeRTOS-Kernel/event_groups.c:413: Error: unknown opcode or format name 'dsb'
.pio/libdeps/denky32/FreeRTOS-Kernel/event_groups.c:413: Error: unknown opcode or format name 'isb'
.pio/libdeps/denky32/FreeRTOS-Kernel/portable/GCC/ARM_CM3/portmacro.h:216: Error: unknown opcode or format name 'mrs'
.pio/libdeps/denky32/FreeRTOS-Kernel/portable/GCC/ARM_CM3/portmacro.h:217: Error: bad register name: 3
.pio/libdeps/denky32/FreeRTOS-Kernel/portable/GCC/ARM_CM3/portmacro.h:217: Error: junk at end of line, first unrecognized character is `3'

please help

**Comment by positron96** [comment]
Hello. `denky32` library has no relation to this project. Please, investigate how it got into `libdeps`.

**Comment by andy0983** [comment]
I get this error after compiling the project

In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/devices/GrblDevice.cpp:1:
lib/FreeRTOS/stream_buffer.h:75:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
lib/FreeRTOS/stream_buffer.h:83:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'

**Comment by andy0983** [comment]
in this file stream_buffer.h there is an error with this struct

75 //////////////////////////////////
typedef struct xSTATIC_STREAM_BUFFER
{
	size_t uxDummy1[ 4 ];
	void * pvDummy2[ 3 ];
	uint8_t ucDummy3;
	#if ( configUSE_TRACE_FACILITY == 1 )
		UBaseType_t uxDummy4;
	#endif
} StaticStreamBuffer_t;

**Comment by positron96** [comment]
Ok, that's useful. Please provide output of compilation headers where it prints versions of toolchains. Also, do you have latest commit of this project? I've recently pinned ESP32 toolchain version, it might help.

**Comment by andy0983** [comment]
Processing denky32 (platform: espressif32; board: denky32; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/denky32.html
PLATFORM: Espressif 32 (4.2.0) > Denky32 (WROOM32)
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20002.220503 (2.0.2)
 - tool-esptoolpy @ 1.30300.0 (3.3.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESP Async WebServer @ 1.2.3
|   |-- AsyncTCP @ 1.1.1
|   |-- ArduinoJson @ 6.19.4
|   |-- FS @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- SD @ 2.0.0
|   |-- FS @ 2.0.0
|   |-- SPI @ 2.0.0
|-- WiFi @ 2.0.0
|-- SPI @ 2.0.0
|-- U8g2 @ 2.34.5
|   |-- SPI @ 2.0.0
|   |-- Wire @ 2.0.0
|-- ArduinoJson @ 6.19.4
|-- AsyncTCP @ 1.1.1
|-- Embedded Template Library @ 20.35.2
|-- FreeRTOS
Building in release mode
Compiling .pio\build\denky32\src\InetServer.cpp.o
Compiling .pio\build\denky32\src\Job.cpp.o
Compiling .pio\build\denky32\src\devices\GCodeDevice.cpp.o
Compiling .pio\build\denky32\src\devices\GrblDevice.cpp.o
Compiling .pio\build\denky32\src\main.cpp.o
Compiling .pio\build\denky32\src\ui\DRO.cpp.o
Compiling .pio\build\denky32\src\ui\Display.cpp.o
Compiling .pio\build\denky32\src\ui\FileChooser.cpp.o
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/Job.h:7,
                 from src/Job.cpp:1:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/Job.h:3,
                 from src/Job.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/Job.h:7,
                 from src/Job.cpp:1:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/Job.h:3,
                 from src/Job.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/devices/GrblDevice.cpp:1:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/devices/GCodeDevice.h:3,
                 from src/devices/GrblDevice.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/devices/GrblDevice.cpp:1:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/devices/GCodeDevice.h:3,
                 from src/devices/GrblDevice.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/devices/GCodeDevice.cpp:1:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/devices/GCodeDevice.h:3,
                 from src/devices/GCodeDevice.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/devices/GCodeDevice.cpp:1:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/devices/GCodeDevice.h:3,
                 from src/devices/GCodeDevice.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
*** [.pio\build\denky32\src\Job.cpp.o] Error 1
*** [.pio\build\denky32\src\devices\GrblDevice.cpp.o] Error 1
*** [.pio\build\denky32\src\devices\GCodeDevice.cpp.o] Error 1
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/Job.h:7,
                 from src/InetServer.cpp:8:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/InetServer.h:3,
                 from src/InetServer.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/Job.h:7,
                 from src/InetServer.cpp:8:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/InetServer.h:3,
                 from src/InetServer.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
*** [.pio\build\denky32\src\InetServer.cpp.o] Error 1
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/ui/../devices/GCodeDevice.h:6,
                 from src/ui/Screen.h:9,
                 from src/ui/FileChooser.h:3,
                 from src/ui/FileChooser.cpp:1:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/ui/Screen.h:3,
                 from src/ui/FileChooser.h:3,
                 from src/ui/FileChooser.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/ui/../devices/GCodeDevice.h:6,
                 from src/ui/Screen.h:9,
                 from src/ui/FileChooser.h:3,
                 from src/ui/FileChooser.cpp:1:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/ui/Screen.h:3,
                 from src/ui/FileChooser.h:3,
                 from src/ui/FileChooser.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/ui/../devices/GCodeDevice.h:6,
                 from src/ui/Display.h:11,
                 from src/ui/Display.cpp:1:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/ui/Display.h:3,
                 from src/ui/Display.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/ui/../devices/GCodeDevice.h:6,
                 from src/ui/Display.h:11,
                 from src/ui/Display.cpp:1:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/ui/Display.h:3,
                 from src/ui/Display.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/main.cpp:7:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/main.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/devices/GCodeDevice.h:6,
                 from src/main.cpp:7:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from src/main.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/ui/../devices/GCodeDevice.h:6,
                 from src/ui/Screen.h:9,
                 from src/ui/DRO.h:6,
                 from src/ui/DRO.cpp:1:
lib/FreeRTOS/stream_buffer.h:74:16: error: redefinition of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from lib/ArduinoJson/src/ArduinoJson.hpp:13,
                 from lib/ArduinoJson/src/ArduinoJson.h:9,
                 from src/ui/DRO.h:3,
                 from src/ui/DRO.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1373:16: note: previous definition 
of 'struct xSTATIC_STREAM_BUFFER'
 typedef struct xSTATIC_STREAM_BUFFER
                ^~~~~~~~~~~~~~~~~~~~~
In file included from lib/FreeRTOS/message_buffer.h:72,
                 from src/CommandQueue.h:5,
                 from src/ui/../devices/GCodeDevice.h:6,
                 from src/ui/Screen.h:9,
                 from src/ui/DRO.h:6,
                 from src/ui/DRO.cpp:1:
lib/FreeRTOS/stream_buffer.h:82:3: error: conflicting declaration 'typedef int StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:33,
                 from lib/ArduinoJson/src/ArduinoJson.hpp:13,
                 from lib/ArduinoJson/src/ArduinoJson.h:9,
                 from src/ui/DRO.h:3,
                 from src/ui/DRO.cpp:1:
C:/Users/ANDY/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:1382:3: note: previous declaration 
as 'typedef struct xSTATIC_STREAM_BUFFER StaticStreamBuffer_t'
 } StaticStreamBuffer_t;
   ^~~~~~~~~~~~~~~~~~~~
*** [.pio\build\denky32\src\ui\FileChooser.cpp.o] Error 1
*** [.pio\build\denky32\src\ui\Display.cpp.o] Error 1
*** [.pio\build\denky32\src\ui\DRO.cpp.o] Error 1
*** [.pio\build\denky32\src\main.cpp.o] Error 1
================================================================= [FAILED] Took 17.32 seconds =================================================================

Environment    Status    Duration
-------------  --------  ------------
denky32        FAILED    00:00:17.323

**Comment by andy0983** [comment]
if I remove this part of the code, there is no error and it compiles but nothing is displayed
 (I checked the settings and connecting the display on another project and it works)

typedef struct xSTATIC_STREAM_BUFFER
{
size_t uxDummy1[ 4 ];
void * pvDummy2[ 3 ];
uint8_t ucDummy3;
#if ( configUSE_TRACE_FACILITY == 1 )
UBaseType_t uxDummy4;
#endif
} StaticStreamBuffer_t;

**Comment by andy0983** [comment]
I really like the design, the housing and the operation, so I decided to do it.
  I hope I will succeed :)

**Comment by positron96** [comment]
Ok, your Espressif 32 platform version is 4.2.0, while the project is written for 3.5.0 at the moment. Could you please try the following:

- remove 4.2.0 platform (should not be necessary, but just to be sure),
- checkout the latest commit of the project,
- clean&build the project.

**Comment by andy0983** [comment]
![image](https://user-images.githubusercontent.com/46644622/204108892-e00e86a6-a1f1-4797-b71e-d5f52cdaea67.png)

**Comment by andy0983** [comment]
I don't know what to do next I have this screen.
I am connected to wifi

**Comment by andy0983** [comment]
I tried to connect esp32 (usb) <--> Arduino (usb) grbl 1.1 but the screen is the same

**Comment by positron96** [comment]
Hi. You need to connect the arduino and ESP32 via UART. For testing purposes, direct cross connection of RX-TX  will work, but for long-term I recommend a 3.3V-5V level shifter.
