### ISSUE TITLE
F360 or STEP files available?

### ISSUE THREAD

**Issue by ArcAIN6** [positron96/ESP32_CNC_Pendant#7]
I'm wondering if the Fusion360 or STEP files are available for the case? The reason i ask, is i'm going to be using a different MCU, and 18650 batteries, and the case as it is is too thin for the batteries.  If i had the STEP or Fusion360 files, i could alter it to suit my needs. 

STL files are notoriously terible to work with, as they don't contain any unit data, and converting STL to solid is a nightmare that almost never works well.

**Comment by positron96** [comment]
Hi. Here is the full assembly
[cnc pendant new v8.zip](https://github.com/positron96/ESP32_CNC_Pendant/files/11760750/cnc.pendant.new.v8.zip)

**Comment by ArcAIN6** [comment]
Thank you!!

**Comment by positron96** [comment]
You're welcome! Very interested in what will your project finally be!

**Comment by ArcAIN6** [comment]
Still have a little ways to go with it (adding the uSD board, BMS board, and a port for serial communication)
[DIY CNC PENDANT v4.zip](https://github.com/positron96/ESP32_CNC_Pendant/files/11819282/DIY.CNC.PENDANT.v4.zip)

**Comment by positron96** [comment]
Very sleek and smooth!

**Comment by ArcAIN6** [comment]
I think this will be the final iteration of this design.. 
As it is, you'll need to desolder the micro-USB from the lolin32-lite, and run wires to a micro-usb breakout board (or if you're lucky enough to find one, use a case-mount micro-usb extension cable, and make a couple of holes in the design files to fit it)

As the Lolin32-lite already has a battery port on it, i've decided to use that, instead of a dedicated charge controller, and 18650's (it's still possible if you want to do that there's plenty of space)

There's enough space left in the clam-shell for a 5v <-> 3.3v level shifter, but mine haven't arrived yet (aliexpress slow af)
You WILL need the level shifter for the screen proposed, as 3.3v will not be enough to see anything on the screen (contrasting issues reeee)

Version Diff:
Cleaned up a LOT of the extraneous faces and un/overlapping faces
Cleaned up hidden cavities
refined the standoff's, and screw posts to be more rigid, and conforming

Because the final zip / f3d file was too large, here's a google drive link to it: 

https://drive.google.com/file/d/1XrvvG77iRPZt9TtEOCKXQYe6BK7cC_K2/view?usp=sharing

**Comment by adalton2636** [comment]
amigo o seu pendent funcionou perfeito se sim poderia min ajuda
