### ISSUE TITLE
Adding custom Button(s).

### ISSUE THREAD

**Issue by amjadali56** [positron96/ESP32_CNC_Pendant#9]
Me again! 
1: Is it possible to add some button like push button for E-stop. coolent on etc?
2: If yes! what will be practical example?
Thanks for such good project.....

**Comment by positron96** [comment]
Hi. 
Yes, definitely possible. Connection would be similar to 3 UI buttons, and code would be similar to menu items that send commands to GRBL. 
Button handlers can go to `Screen::onButtonPress` (for buttons that need to function always, e.g. e-stop), and to `DRO::onButtonPress` for others

**Comment by amjadali56** [comment]
explain please.... I coudn't made it working....... 
for example i need E-stop button 
pinMode(PIN_BT4, INPUT_PULLUP);         

and button for zero XY 
pinMode(PIN_BT5, INPUT_PULLUP);

**Comment by positron96** [comment]
Hi. I don't quite understand how I can help you without writing the code myself, which I don't have time for. Could you make a fork with what you've done so far and invite me to read it?
